### PR TITLE
Implemented arbitrary pointwise initial conditions in analytic solver

### PR DESCRIPTION
**Pull request by ntardiff**
Hi Max,

Congrats on the PyDDM paper getting published!

This pull request implements the ability to use the analytic solver for models with arbitrary pointwise initial conditions.

A couple of notes:
- In order to allow more flexibility for using the analytic solver with custom code, I changed models.has_analytical_solution() to return true as long as the Bound and IC model components are subclasses of acceptable built-in PyDDM classes. This puts some onus on the user to not do anything ridiculous, but greatly increases the number of cases in which you could try using the analytic solver.
- The analytic solution really breaks down when the initial conditions get too close to one of the bounds, and you end up w/ a lot of undecided probability mass. The numerical solver seems more robust in this regard, but in practice I'm not sure this is much of an issue since if you had initial conditions that close to the bound you'd have to wonder whether there was any evidence accumulation happening in your subject data at all. I don't understand the analytical algorithm well enough to know whether anything could be done to mitigate this issue.
- I've attached code that if run show very similar solutions when solving the same model (start shift and linear collapsing bounds) with the analytic and numerical solvers: [analytic_start_shift_example.txt](https://github.com/mwshinn/PyDDM/files/5086630/analytic_start_shift_example.txt)
- As a further check I also refit a model on example subject data that  I'd initially fit using the numerical solver and recovered very similar parameter values.

### CODE REVIEW

**Comment by mwshinn** [comment]
Hi Nathan,

Thank you, and thank you for your PR - this looks awesome!  A few things before I merge it:

1. Could you please make a unit test for a couple cases, just to make sure the analytical solution continues to match?  You can reuse your code in the .txt file, but make sure to do one case with constant bounds and one case with linearly collapsing bounds.

2. I don't think looking for subclasses for the bounds is a good idea.  The reason is that someone may inherit from one of the bounds classes and give it different behavior, which could cause undetected errors.  Undetected errors in scientific software should be avoided at all costs.  For the linearly collapsing bounds, the current implementation relies on a specific parameter value, so if that parameter has a different meaning in the subclass, it will cause an undetected error, so I think this one (at least for right now) should be tested for equality until a more robust solution is in place.  However, if you want to generalize the mechanism for the constant bounds case, could you please test whether "t" is an argument for the method?  You can see the tests for Drift and Noise as examples.

Testing for subclasses of IC (as you are doing now) is okay, because this would not cause undetected errors, it would simply throw an assert error, which is fine.  It's not ideal, and at some point when the autodetection code is improved this should be changed, but it's good enough for now and I can't think of a better solution.

3. When you say, "The analytic solution really breaks down when the initial conditions get too close to one of the bounds", how close to the boundary does the analytic solution start to break down?  E.g. if the boundary was 1, does it start to break down as .9, .95, .99, .999, ...?

**Comment by ntardiff** [comment]
1. Sure. This should go in integration_tests.py?

2. Yeah, I didn't think this was necessarily ideal I just couldn't think of a better way to do it. I'm a little unclear on what you're proposing in checking for a "t" argument. In the Drift and Noise cases, this is an exclusion criteria--it would be pretty permissive as an inclusion criteria, no? But maybe I'm misunderstanding. I was going to suggest checking if the correlation between t_domain and get_bound(t_domain) == -1, but that would have to be done in solve_analytical() not has_analytical_solution() since it could be condition-dependent... 

3. I think this is going to depend to some extent on the other parameters, but it looks like for a constant bound of 1 and dt of .001 it's around +/- .95 that you start losing probability mass; as you get closer to +/- 1.0 renormalization warnings and negative probability warnings start popping up as well. Essentially it's treating the almost instantaneous crossing of the bound as undecided. I verified this by increasing dt to .0001, which helped but is obviously not practical. 

In less extreme parameter ranges the models match quite closely..they might differ slightly in the exact shape of the distributions or the amount of mass assigned to correct vs. error, but not by much.

**Comment by mwshinn** [comment]
1. Yes, integration_test.py would be perfect!

2. For testing for "t", I'm proposing two different solutions: one for linearly collapsing bounds, and the other for constant bounds.  For the linearly collapsing bounds, I'm proposing testing for equality, because the implementation within the analytic solver accesses a specific variable.  So if you inherit from BoundsCollapsingLinear and then do something different with the "t" parameter, PyDDM will give an erroneous result.  Like you say, this is a tricky problem to solve and I don't think that we should try to find a solution to this now.  I would rather PyDDM be more restrictive than to have the possibility of giving an erroneous result.

For the constant bounds case, which is easier, I'm proposing to check whether the get_bound method asks for an argument "t".  If it doesn't, then that means the boundary is constant given conditions and parameters, which should be sufficient for the analytical solver.  This is in line with the implementation of how we check whether drift rate depends on space or time, i.e.

```
        driftfuncsig = inspect.signature(mt["Drift"].get_drift)
        if "t" in driftfuncsig.parameters or "x" in driftfuncsig.parameters:
```

See https://pyddm.readthedocs.io/en/latest/faqs.html#what-arguments-do-get-drift-get-noise-etc-take for more details.

3. Okay, sounds good.  If it is triggering the warning to decrease dt, that should be sufficient.

**Comment by mwshinn** [comment]
Oh, and one more point on (3): the most important thing is that it converges to the correct result, i.e. as you decrease dt in the analytical and numerical solutions, the solutions get closer together.  From what you say, it sounds like this is the case.  There's no good way to test this automatically in a unit test, though, but good to confirm.

**Comment by ntardiff** [comment]
1. & 3. I added the unit tests. These pass, but they would fail given other parameter values (at least w/o increasing dt) at the thresholds used for for other calls to _modeltest_numerical_vs_analytical(). But the solutions definitely get closer together when increasing dt. I've also noticed that you can get large max differences in the solutions when mean differences are very small and differences in predicted probabilities are very small, just based on slight differences in the rise and fall around the mode of the distribution. 

I would also note that the analytical solution starts losing probability mass before the warnings occur--I think the warnings only occur when it gets more extreme. Not knowing anything more about the algorithm, I'm not sure what could be done about this besides always using a very high time resolution near the boundaries...though I'm pretty confident the current implementation will work appropriately in realistic cases.

2. I changed the criteria as you suggested. Let me know if this wasn't what you meant. This also necessitated a slight change to solve_analytical() to allow for constant bounds implemented in classes other than BoundConstant.

**Comment by mwshinn** [comment]
This looks great, thank you for your contribution!  This feature will be very useful to a number of PyDDM users!  It should be available on pip in the coming weeks once we release v0.5.0.

**Comment by ntardiff** [comment]
Awesome. You're welcome! I'm very happy to be able to contribute!

**Pull request merged**
